apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultserver
  name: resultserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver
  strategy: {}
  template:
    metadata:
      labels:
        app: resultserver
    spec:
      containers:
      - image: ozgurtaylankarakoc/resultserver:1.0
        name: result-server
        ports:
          - containerPort: 80
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
        envFrom:
          - configMapRef:
              name: webserver-configmap
        resources: {}