apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/mysql-data"